# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b575fe3d3abeb6bf12bb6e1e418f7e1e90d27ecc050b79259cb7e13b0f0dbab70e5f93bd7e19927fd16a1078753b3f9cc9ad34129d00a3b981b8290b67325dac

test:
  secret_key_base: d0405adf50d01117ff7dcea47c4b828cc12bc59b1de9636d2945727d4184a611c7e717a53bf9b0f3d11e161c0020664d5325a150c0457f8dd916789286dfec9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
